
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./src/exports:/app/src/exports

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongo-data:
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     env_file: .env
#     volumes:
#       - ./src/exports:/app/src/exports
